type: object
required:
  - giterminismConfigVersion
additionalProperties: {}
properties:
  giterminismConfigVersion:
    type: string
    enum: ["1"]
  config:
    $ref: '#/definitions/Config'
  helm:
    $ref: '#/definitions/Helm'
definitions:
  Config:
    type: object
    additionalProperties: {}
    properties:
      allowUncommitted:
        type: boolean
      allowUncommittedTemplates:
        type: array
        items:
          type: string
      goTemplateRendering:
        $ref: '#/definitions/ConfigGoTemplateRendering'
      stapel:
        $ref: '#/definitions/ConfigStapel'
      dockerfile:
        $ref: '#/definitions/ConfigDockerfile'
  ConfigGoTemplateRendering:
    type: object
    additionalProperties: {}
    properties:
      allowEnvVariables:
        type: array
        items:
          type: string
  ConfigStapel:
    type: object
    additionalProperties: {}
    properties:
      allowFromLatest:
        type: boolean
      git:
        $ref: '#/definitions/ConfigStapelGit'
      mount:
        $ref: '#/definitions/ConfigStapelMount'
  ConfigStapelGit:
    type: object
    additionalProperties: {}
    properties:
      allowBranch:
        type: boolean
  ConfigStapelMount:
    type: object
    additionalProperties: {}
    properties:
      allowBuildDir:
        type: boolean
      allowFromPaths:
        type: array
        items:
          type: string
  ConfigDockerfile:
    type: object
    additionalProperties: {}
    properties:
      allowUncommitted:
        type: array
        items:
          type: string
      allowUncommittedDockerignoreFiles:
        type: array
        items:
          type: string
      allowContextAddFile:
        type: array
        items:
          type: string
  Helm:
    type: object
    additionalProperties: {}
    properties:
      allowUncommittedFiles:
        type: array
        items:
          type: string