stages:
    - build
    - deploy

variables:
    WERF_STAGES_STORAGE: ":local"

before_script:
  - type multiwerf && source <(multiwerf use 1.1 stable)
  - type werf && source <(werf ci-env gitlab --verbose)

Build:
  stage: build
  script:
    - werf build-and-publish
  tags:
    - werf
  except:
    - schedules

.base_deploy:
  stage: deploy
  script:
    - werf deploy
      --set "global.ci_url=$(echo ${CI_ENVIRONMENT_URL} | cut -d / -f 3)"
  dependencies:
    - Build
  tags:
    - werf
  except:
    - schedules

Deploy to stage:
  extends: .base_deploy
  environment:
    name: stage
    url: http://example-2-stage.kube.example.com
  only:
    - merge_requests
  when: manual

Deploy to production:
  extends: .base_deploy
  environment:
    name: production
    url: http://example-2.kube.example.com
  only:
    - master

