dist: xenial
language: ruby
cache:
  bundler: true
  directories:
    - ~/go
    - ~/gopath
rvm:
  - 2.5

install:
  - mkdir -p ~/gopath/src/github.com/flant/ && mv $TRAVIS_BUILD_DIR ~/gopath/src/github.com/flant/dapp && ln -fs ~/gopath/src/github.com/flant/dapp $TRAVIS_BUILD_DIR
  - if [ ! -f ~/go/installed ]; then wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz -O /tmp/go.tar.gz ; tar -C ~/ -xzf /tmp/go.tar.gz ; touch ~/go/installed ; fi
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - export GOROOT=~/go
  - export GOPATH=~/gopath
  - export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"
  - export CGO_ENABLED=0
  - export GOOS=linux
  - which go
  - go version
  - ./go-get.sh && ./go-build.sh

deploy:
  provider: script
  script: ./publish.sh --tag $TRAVIS_TAG
  on:
    tags: true
