configVersion: 1
project: ansible-apt-mark-panic-1820

---
image: ubuntu-22-04
from: registry.werf.io/base/ubuntu:22.04
ansible:
  install:
  - name: Install essential utils
    apt:
      name: apt-transport-https
      update_cache: yes
