# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
  en:
    f:
      - title: Back to documentation
        url: /documentation/index.html

  ru:
    f:
      - title: Назад к документации
        url: /documentation/index.html

      - title: К выбору языка и CI-системы
        url: /documentation/guides/applications-guide/

      - title: Оглавление
        sf:

          - title: Как использовать гайд
            url: /documentation/guides/applications-guide/gitlab-rails/000-task.html

          - title: Подготовка к работе
            url: /documentation/guides/applications-guide/gitlab-rails/010-preparing.html
            sfi:
              - title: Подготовка приложения
                hash: "#preparing-app"
              - title: Подготовка среды
                hash: "#preparing-env"

          - title: Базовые настройки
            url: /documentation/guides/applications-guide/gitlab-rails/020-basic.html
            sfi:
              - title: Локальная сборка
                hash: "#hello-world-local"
              - title: Построение CI-процесса
                hash: "#hello-world-ci"
                sfi:
                - title: Сборка в Gitlab CI
                  hash: "#hello-world-ci-build"
                - title: Деплой в Kubernetes
                  hash: "#hello-world-ci-deploy"

          - title: Подключаем зависимости
            url: /documentation/guides/applications-guide/gitlab-rails/030-dependencies.html
            sfi:
              - title: Подключение менеджера зависимостей
                hash: "#dependencies-implementation"
              - title: Оптимизация сборки
                hash: "#dependencies-optimization"

          - title: Генерируем и раздаём ассеты
            url: /documentation/guides/applications-guide/gitlab-rails/040-assets.html
            sfi:
              - title: Сценарий сборки ассетов
                hash: "#assets-scenario"
              - title: Какие изменения необходимо внести
                hash: "#assets-implementation"

          - title: Работа с файлами
            url: /documentation/guides/applications-guide/gitlab-rails/050-files.html

          - title: Работа с электронной почтой
            url: /documentation/guides/applications-guide/gitlab-rails/060-email.html

          - title: Подключаем Redis
            url: /documentation/guides/applications-guide/gitlab-rails/070-redis.html
            sfi:
              - title: Завести Redis в Kubernetes
                hash: "#redis-to-kubernetes"
              - title: Подключение приложения к Redis
                hash: "#redis-to-app"

          - title: Подключаем базу данных
            url: /documentation/guides/applications-guide/gitlab-rails/080-database.html
            sfi:
              - title: Общий подход
                hash: "#database-generic"
              - title: Подключение приложения к базе данных
                hash: "#database-app-connection"
              - title: Выполнение миграций
                hash: "#database-migrations"
              - title: Накатка фикстур
                hash: "#database-fixtures"

          - title: Юнит-тесты и Линтеры
            url: /documentation/guides/applications-guide/gitlab-rails/090-unittesting.html

          - title: Несколько приложений в одной репе
            url: /documentation/guides/applications-guide/gitlab-rails/110-multipleapps.html

          - title: Динамические окружения
            url: /documentation/guides/applications-guide/gitlab-rails/120-dynamicenvs.html




