priorityClassName:
  _default: develop
  production: production-medium
host:
  production: werf.io
  dev: werf.dev.flant.dev
  _default: werf.test.flant.dev

ingressSecretName:
  _default: wildcard-dev-flant-dev
  test: wildcard-test-flant-dev
  stage: wildcard-stage-flant-dev

ingressClassName:
  _default: "nginx"
  production: "standalone-geo"

resources:
  requests:
    memory:
      _default: 20M
      production: 50M
