version: "3.9"

services:
  documentation:
    image: $WERF_WEB_DOCKER_IMAGE_NAME
    command: ["nginx", "-g", "daemon off;"]

  front:
    image: nginx:latest
    volumes:
      - ".werf/nginx-dev-slow.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - documentation

