name: Trdl releaser
on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Perform werf release using trdl server
    runs-on: ubuntu-latest
    steps:
    - name: Prepare git info
      id: git_info
      run: |
        echo ::set-output name=GIT_TAG::${GITHUB_REF#refs/tags/}
    - name: Release
      uses: werf/trdl-vault-actions/release@main
      with:
        vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
        project-name: werf
        git-tag: ${{ steps.git_info.outputs.GIT_TAG }}
        vault-auth-method: approle
        vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
        vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}
