name: Review website
on:
  pull_request:
    types: [labeled, synchronize]

env:
  WERF_SET_ACTIVE_RELEASE: "global.active_release=1.2"
  WERF_REPO: ${{ secrets.WERF_REGISTRY_SERVER }}/werf/werfio

jobs:

  converge:
    name: Converge to Review
    runs-on: tfprod-werf
    if: github.event.label.name == 'review docs' || contains( github.event.pull_request.labels.*.name, 'review docs' )
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to werf registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.WERF_REGISTRY_SERVER }}
        username: ${{ secrets.WERF_REGISTRY_USERNAME }}
        password: ${{ secrets.WERF_REGISTRY_PASSWORD }}

    - name: Message
      run: |
          echo "Temporarily disabled"

