name: Review website
on:
  pull_request:
    types: [labeled, synchronize]

env:
  WERF_SET_ACTIVE_RELEASE: "global.active_release=1.2"
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/werfio"

jobs:

  converge:
    name: Converge to Review
    runs-on: tfprod-werf
    if: github.event.label.name == 'review docs' || contains( github.event.pull_request.labels.*.name, 'review docs' )
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Message
      run: |
          echo "Temporarily disabled"

